version: "3.9"

services:

  db:
    image: mysql:8.0.24
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - 'MYSQL_ROOT_PASSWORD=${DB_PASSWORD}'
      - 'MYSQL_DATABASE=${DB_DATABASE}'
    ports:
      - "3306:3306"


volumes:
  mysql_data:
    driver: local
